default_platform(:ios)

platform :ios do
  desc "Creates xcframework using carthage and its zip file"
  lane :build_framework do
    carthage(command: "build", no_skip_current: true, use_xcframeworks: true)
    zip(path: "Carthage/Build/YMChat.xcframework", output_path: "Carthage/Build/YMChat.xcframework.zip", verbose: false)
  end

  desc "Check if the new version is already used in the files"
  lane :valid_version do |options|
    target_version = options[:version]

    raise "Xcode project is already at the said version" if get_version_number == target_version
    # raise "podspec is already at the said version" if git_tag_exists(tag: target_version)
    raise "podspec is already at the said version" if version_get_podspec == target_version
    true
  end

  desc "Creates release using the version passed"
  lane :release do |options|
    update_type = options[:update]
    raise "Use fastlane release bump:(major|minor|path)" unless ['major', 'minor', 'patch'].include? (update_type)
    
    ensure_git_status_clean
    
    ensure_git_branch(branch: 'main')
    
    # test if xcode build is successful
    
    # increment_build_number # automatically increment by one
    target_version = increment_version_number(bump_type: update_type)
    puts("New version = #{target_version}")
    valid_version(options: target_version)
    
    build_framework
    
    version_bump_podspec(version_number: target_version)

    pod_lib_lint
    
    commit_version_bump(message: "Version bump", include: "YMChat.podspec")

    add_git_tag(tag: target_version)
    
    push_to_git_remote # will do push_git_tags also

    pod_push

    # create release on github with target_version
    github_release = set_github_release(
      repository_name: "yellowmessenger/YMChatbot-iOS",
      api_token: ENV["GITHUB_TOKEN"],
      name: target_version,
      tag_name: target_version,
      commitish: "master",
      upload_assets: ["Carthage/Build/YMChat.xcframework.zip"]
   )

    # create fat framework

    # create release on github with target_version
    # attach xcframework.zip and fat-framework.zip to the release

  end
end
